config/routes.rb
Rails.application.routes.draw do

  root "playlists#index"
  resources :users, except: [:index]
  resources :playlists do
    resources :comments, only: [:create, :destroy]
  end
  resource :session, only: :create

  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  
  get "/auth/spotify/callback", to: "playlists#spotify", as: "spotify"

  post "follow/:playlist_id", to: "follows#create", as: "follow"
  delete "follow/:playlist_id", to: "follows#destroy", as: "unfollow"

  post "like/:playlist_id", to: "likes#create", as: "like"
  delete "like/:playlist_id", to: "likes#destroy", as: "unlike"

  get 'playlists/filter/:filter', to: 'playlists#index', as: 'filtered_playlists'
end

app/models/user.rb
class User < ApplicationRecord

  REGEX_PATTERN = /^(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}$/i

  has_secure_password

  validates :email, :username, presence: true, 
            uniqueness: { case_sensitive: false }
  validates :email, format: { with: /#{REGEX_PATTERN}/ }
  validates :username, length: { minimum: 3 }, 
            format: { with: /\A[A-Z0-9]+\z/i }

  has_many :follows, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_playlists, through: :likes, source: :playlist
  has_many :comments, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @user = User.all
  end

  def show
    @likes = current_user.liked_playlists.with_attached_playlist_image
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account Created!"
    else
      flash.now[:alert] = "There are errors in the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile updated!"
    else
      flash.now[:alert] = "There are errors in the form."
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:email, :username, :password,
                                   :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>

<div class="field">
  <%= f.label :email, class: "label" %>
  <%= f.text_field :email, class: "control input" %>
</div>


<div class="field">
  <%= f.label :username, class: "label" %>
  <%= f.text_field :username, class: "control input" %>
</div>

<div class="field">
  <%= f.label :password, class: "label" %>
  <%= f.password_field :password, class: "control input" %>
</div>

<div class="field">
  <%= f.label :password_confirmation, "Confirm Password", 
              class: "label" %>
  <%= f.password_field :password_confirmation, class: "control input" %>
</div>

<div class="field">
  <% if user.new_record? %>
    <%= f.submit "Create Account", class: "control button is-success has-text-weight-semibold" %>
  <% else %>
        <%= f.submit "Update Profile", class: "control button is-primary has-text-weight-semibold" %>
  <% end %>
</div>

<% end %>

app/views/users/edit.html.erb
<section class="section">
  <h1 class="title has-text-weight-bold">Edit Profile</h1>
  <div class="columns">
    <div class="column is-one-third">
      <% if @user.errors.any? %>
        <div class="box">
          <div class="content">
            <ol type="1">
              <% @user.errors.full_messages.each do |e| %>
                  <li><%= e %></li>
              <% end %>
            </ol>
          </div>
        </div>
      <% end %>
      <%= render 'form', user: @user %>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="section">
  <h1 class="title has-text-weight-bold">Sign Up</h1>
  <div class="columns">
    <div class="column is-one-third">
      <% if @user.errors.any? %>
        <div class="box">
          <div class="content">
            <ol type="1">
              <% @user.errors.full_messages.each do |e| %>
                  <li><%= e %></li>
              <% end %>
            </ol>
          </div>
        </div>
      <% end %>
      <%= render 'form', user: @user %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section has-text-white">
  <p><strong class="has-text-weight-bold has-text-white">Email:</strong> <%= current_user.email%></p>
  <p><strong class="has-text-weight-bold has-text-white">Username:</strong> <%= current_user.username %></p>
  <p><strong class="has-text-weight-bold has-text-white">Joined:</strong> <%= time_ago_in_words(current_user.created_at) %> ago</p>
  <%= link_to "Edit Profile", edit_user_path, class: "button mt-5" %>
</section>
<section class="section">
  <h1 class="title has-text-weight-bold">Likes</h1>
  <div class="columns is-multiline">
    <% @likes.each do |l| %>
      <div class="column is-one-fifth">
        <div class="card">
          <div class="card-image">
            <figure class="image is-1by1">
              <%= link_to image_tag(l.playlist_image), l %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="subtitle is-6 has-text-weight-bold"><%= pretty_title(l.name) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>