config/routes.rb
Rails.application.routes.draw do

  root "playlists#index"
  resources :users, except: [:index]
  resources :playlists do
    resources :comments, only: [:create, :destroy]
  end
  resource :session, only: :create

  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  
  get "/auth/spotify/callback", to: "playlists#spotify", as: "spotify"

  post "follow/:playlist_id", to: "follows#create", as: "follow"
  delete "follow/:playlist_id", to: "follows#destroy", as: "unfollow"

  post "like/:playlist_id", to: "likes#create", as: "like"
  delete "like/:playlist_id", to: "likes#destroy", as: "unlike"

  get 'playlists/filter/:filter', to: 'playlists#index', as: 'filtered_playlists'
end

app/models/playlist.rb
require 'open-uri'

class Playlist < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :tracks, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_one_attached :playlist_image, dependent: :destroy


  scope :chronological, -> { with_attached_playlist_image
                             .order("created_at desc") }
  scope :popular, -> { left_joins(:likes)
                       .select('playlists.*, COUNT(playlist_id) AS count_of_likes')
                       .group('playlists.id')
                       .with_attached_playlist_image
                       .order('count_of_likes DESC') }

  def self.prepare_playlist(params)
    playlist = Playlist.new
    spotify_object = playlist.get_spotify_object(params)
    playlist.populate_attributes(spotify_object, params)
    spotify_object.tracks.each do|track|
      playlist.tracks.new(
        title: track.name, 
        artist: track.artists.first.name
      )
    end
    playlist
  end

  def self.search_playlists(playlist)
    RSpotify::Playlist.search(playlist)
  end

  def attach_image(params)
    spotify_object = get_spotify_object(params)
    open(spotify_object.images.first['url']) do |file|
      playlist_image.attach(io: file, filename: "#{name}_playlist_image")
    end
  end

  def populate_attributes(spotify_object, params)
    self.name = spotify_object.name.split("OST")[0].strip
    self.spotify_id = params[:playlist_id] ? params[:playlist_id] : params[:playlist][:id].split("spotify:playlist:").first
  end

  def get_spotify_object(params)
    if params[:playlist]
      id = params[:playlist][:id].split("spotify:playlist:")[1]
    elsif params[:playlist_id]
      id = params[:playlist_id]
    end
    RSpotify::Playlist.find_by_id(id)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show, :spotify, :follow_playlist]
  before_action :authorize, only: [:create]

  def index
    case params[:filter]
    when "popular"
      @playlists = Playlist.popular.paginate(page: params[:page], per_page: 12)
    else
      @playlists = Playlist.chronological.paginate(page: params[:page], per_page: 12)
    end
    if current_user
      @follows = current_user.follows.map { |f| f.playlist_id }
      @likes = current_user.likes.map { |l| l.playlist_id }
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @tracks = Track.where("playlist_id = ?", @playlist.id)
    if current_user
      @like = current_user.likes.find_by(playlist_id: @playlist.id)
    end
    @comment = Comment.new
    @comments = Comment.where(playlist_id: params[:id])
  end

  def new
    if params[:playlist_name]
      @playlists = Playlist.search_playlists(params[:playlist_name])
    end
    @playlist = Playlist.new
  end

  def create
    playlist = Playlist.prepare_playlist(params)
    if playlist.save
      playlist.attach_image(params)
      redirect_to root_url, notice: "Successfully added playlist!"
    else
      render :new, alert: "There's a problem with the ID."
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    redirect_to root_url, notice: "Playlist deleted."
  end

  def spotify
    session[:spotify_user] = RSpotify::User.new(request.env['omniauth.auth'])
    redirect_to root_url
  end

  private

    def authorize
      RSpotify.authenticate(ENV["spotify_key"], ENV["spotify_secret"])
    end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def youtube_search_link(track)
    link_to track.title, 
      "https://www.youtube.com/results?search_query=#{track.title}+#{track.artist}",
      target: :_blank
  end

  def pretty_title(title)
    title.split.map(&:upcase).join(' ')
  end
end

app/views/playlists/_card.html.erb
<div class="column is-3-desktop is-4-tablet">
  <div id="test" class="card">
    <div class="card-image">
      <figure class="image is-1by1">
        <%= link_to image_tag(p.playlist_image), p %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-6 has-text-weight-bold"><%= pretty_title(p.name) %></p>
          <p class="subtitle is-6"><%= p.tracks.size %> tracks</p>
          <div class="level is-mobile">
            <div class="level-left">
              <% unless session[:spotify_user].nil? %>
                <div class="level-item mr-1">
                  <%= turbo_frame_tag "#{dom_id(p)}_follow_button" do %>
                    <% if follows && follows.include?(p.id) %>
                      <%= button_to "Unfollow", unfollow_path(p), class: "button is-danger is-small", 
                      method: :delete %>
                    <% elsif current_user %>
                      <%= button_to "Follow on Spotify", follow_path(p), class: "button is-success is-small" %>
                    <% end%>
                  <% end %>
                </div>
              <% end %>
              <div class="level-item">
                <%= turbo_frame_tag "#{dom_id(p)}_like_button" do %>
                  <% if likes && likes.include?(p.id) %>
                      <%= button_to "Unlike", unlike_path(p), class: "button is-link is-small", 
                          "data-turbo-frame": "#{dom_id(p)}_likes", method: :delete %>
                  <% elsif current_user %>
                      <%= button_to "Like ❤️", like_path(p), class: "button is-link is-small", 
                          "data-turbo-frame": "#{dom_id(p)}_likes" %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="level-right">
            </div>
          </div>   
          <div class="level is-mobile">
            <div class="level-left">
              <div class="level-item">
                <p class="is-size-7 is-family-secondary">
                Added <%= time_ago_in_words p.created_at %> ago
                </p>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <p class="is-size-7">
                  <%= turbo_frame_tag "#{dom_id(p)}_likes" do %>
                    <%= render partial: "likes/like_count", locals: { p: p } %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>   
        </div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |f| %>
  <div class="field">
    <%= f.label :id, "Spotify URI (e.g. 'spotify:playlist:1mjzvebZWb4LVrYBMcqyAr')", class: "label" %>
    <div class="control">
        <%= f.text_field :id, class: "input", autocomplete: "off" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit class: "button is-primary has-text-weight-semibold" %>   
    </div>
  </div>
<% end %>

<br>

<%= form_with(url: new_playlist_url, local: true, method: :get) do |f| %>
  <div class="field">
    <%= f.label :playlist_name, "Playlist Name", class: "label" %>
    <div class="control">
      <%= f.text_field :playlist_name, class: "input", autocomplete: "off" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button "Search", class: "button control is-primary has-text-weight-semibold", data: { disable_with: "Searching..." } %>   
    </div>
  </div>
<% end %>

<% if @playlists.present? %>
  <div class="content">
    <ul>
      <%= render partial: "playlist", collection: @playlists %>
    </ul>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<li>
  <%= link_to playlist.name, playlists_path(playlist_id: playlist.id), 
      method: :post, class: "has-text-link has-text-weight-semibold" %> :: 
  <%= playlist.followers["total"] %> followers
</li>

app/views/playlists/_track.html.erb
<tr>
    <td class="is-flex is-align-items-center">
        <%= youtube_search_link(track) %>
    </td>
    <td><%= track.artist %></td>
</tr>

app/views/playlists/index.html.erb
<div class="hero-body">
  <div class="columns is-multiline">
    <%= render partial: "card", collection: @playlists, as: :p, locals: { follows: @follows, likes: @likes } %>
  </div>
    <%= will_paginate @playlist, class: "apple_pagination" %>
</div>

app/views/playlists/new.html.erb
<section class="section">
  <h1 class="title has-text-weight-bold">Add OST</h1>
  <div class="columns">
    <div class="column is-one-third">
      <%= render 'form', playlist: @playlist %>
    </div>
  </div>
</section>

app/views/playlists/show.html.erb
<section class="hero is-primary is-bold">
  <div class="hero-body">
    <h1 class="title has-text-weight-bold">
      <%= @playlist.name.upcase %>
    </h1>
  </div>
</section>
<section class="section">
<div class="columns">
  <div class="column is-half">
    <table class="table is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th>Title</th>
          <th>Artist</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "track", collection: @tracks  %>
      </tbody>
    </table>
  </div>
  <div class="column is-half">
    <%= content_tag(:iframe,'', width: 300, height: 380, src: "https://open.spotify.com/embed/playlist/#{@playlist.spotify_id}") %>
  </div>
</div>
</section>
<section class="section">
<div class="columns">
  <div class="column is-half">
    <% if current_user %>
      <h1 class="title is-4">
        Leave a Comment
      </h1>
      <article class="media">
        <div class="media-content">
          <div class="field">
            <%= form_with model: [@playlist, @comment], local: true do |f| %>
              <div class="field">
                <%= f.text_area :message, placeholder: "Add a comment", 
                    class: "control textarea" %>
              </div>
              <div class="field">
                <%= f.submit "Post Comment", class: "control button is-primary has-text-weight-semibold" %>
              </div>
            <% end %>
          </div>
        </div>
      </article>
    <% else %>
      <h1 class="title is-4">
        Log In to Leave a Comment
      </h1>
    <% end %>
    <% if @comments.any? %>
    <ul class="mt-3">
      <% @comments.each do |c| %>
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= c.user.username %></strong>
                <small><%= time_ago_in_words(c.created_at) %> ago</small>
                <br>
                <%= c.message %>
              </p>
            </div>
          </div>
          <% if current_user && c.user == current_user %>
          <div class="media-right">
            <%= button_to "X", playlist_comment_path(@playlist, c), 
                class: "button is-small is-rounded is-danger", method: :delete %>
          </div>
          <% end %>
        </article>
      </div>
      <% end %>
    </ul>
  <% end %>
  </div>
</div>
</section>
<section class="section">
<% if current_user_admin? %>
  <%= button_to "Delete Playlist", playlist_path, method: :delete,
      data: { confirm: "Are you sure?" }, class: "button is-danger" %>
<% end %>
</section>