config/routes.rb
Rails.application.routes.draw do

  root "playlists#index"
  resources :users, except: [:index]
  resources :playlists do
    resources :comments, only: [:create, :destroy]
  end
  resource :session, only: :create

  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  
  get "/auth/spotify/callback", to: "playlists#spotify", as: "spotify"

  post "follow/:playlist_id", to: "follows#create", as: "follow"
  delete "follow/:playlist_id", to: "follows#destroy", as: "unfollow"

  post "like/:playlist_id", to: "likes#create", as: "like"
  delete "like/:playlist_id", to: "likes#destroy", as: "unlike"

  get 'playlists/filter/:filter', to: 'playlists#index', as: 'filtered_playlists'
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |name, msg| %>
    <% case name.to_sym %>
      <% when :notice %>
        <%= content_tag :div, msg, class: "notification is-primary" %>
      <% when :alert %>
        <%= content_tag :div, msg, class: "notification is-danger" %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      © <%= Time.now.year %> Dillon O'Connor
    </p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <%= link_to image_tag("soundtrack.png", alt: "OST logo"), root_path %>
    </div>
    <div class="navbar-item">
      <%= link_to "Drama OSTs", root_path, 
          class: "navbar-item has-text-weight-bold has-text-white is-uppercase" %>
    </div>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu is-family-secondary">
    <div class="navbar-start">
      <%= link_to "Add OST", new_playlist_path, class: "navbar-item" %>
      <%= link_to "Most Liked", filtered_playlists_path(:popular), class: "navbar-item" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="is-grouped">
          <% if current_user %>
            <%= link_to current_user.username, current_user, class: "button has-text-weight-semibold" %>
            <%= link_to "Sign Out", logout_path, class: "button has-text-weight-semibold",
                        method: :delete %>
          <% else %>
            <%= link_to "Sign Up", new_user_path, class: "button has-text-weight-semibold" %>
            <%= link_to "Log In", login_path, class: "button has-text-weight-semibold" %>
          <% end %>
          <% if current_user && session[:spotify_user].nil? %>
            <%= link_to 'Link Spotify', '/auth/spotify', class: "button is-success has-text-weight-semibold" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OST</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Roboto&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>